### ISSUE TITLE
issue on HPC with  singularity, slurm, and multiCPU

### ISSUE THREAD

**Issue by sbonaime** [OpenDroneMap/NodeMICMAC#69]
On our HPC and with singularity and slurm, I can start a NodeMICMAC with one CPU. Here is the log

````
 SDK releases are limited to address critical bug fixes and security issues only.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
````
I use this slurm script to start it
````
#SBATCH -J NodeMICMAC
#SBATCH --partition=ncpulong,ncpu
#SBATCH --nodes=1
#SBATCH --mem=10G
#SBATCH --ntasks-per-node=1  # MPI per node
#SBATCH --output /gpfs/users/bonaime/logs/logs_nodeodm-%j.out

cd /gpfs/scratch/bonaime/git/NodeMICMAC

srun --nodes=1 singularity run --bind $PWD:/var/www  nodemicmac_latest.sif  $

````

But when I use more than one CPU, here is the log ( for 2 CPUs):
````
(node:2348168) NOTE: The AWS SDK for JavaScript (v2) is in maintenance mode.
 SDK releases are limited to address critical bug fixes and security issues only.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2348159) NOTE: The AWS SDK for JavaScript (v2) is in maintenance mode.
 SDK releases are limited to address critical bug fixes and security issues only.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Authentication using NoTokenRequired
warn: Progress listener server error: Error: bind EADDRINUSE 0.0.0.0:6367
    at dgram.js:357:20
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
events.js:377
      throw er; // Unhandled 'error' event
      ^



Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (/var/www/node_modules/express/lib/application.js:635:24)
    at commands (/var/www/index.js:885:22)
    at /var/www/node_modules/async/dist/async.js:3883:24
    at replenish (/var/www/node_modules/async/dist/async.js:1014:17)
    at iterateeCallback (/var/www/node_modules/async/dist/async.js:998:17)
    at /var/www/node_modules/async/dist/async.js:972:16
    at /var/www/node_modules/async/dist/async.js:3888:13
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
srun: error: ncpu004: task 1: Exited with exit code 1
`````
I use this slurm script to start it. The only difference is in ntasks-per-node
````
#SBATCH -J NodeMICMAC
#SBATCH --partition=ncpulong,ncpu
#SBATCH --nodes=1
#SBATCH --mem=10G
#SBATCH --ntasks-per-node=2  # MPI per node
#SBATCH --output /gpfs/users/bonaime/logs/logs_nodeodm-%j.out

cd /gpfs/scratch/bonaime/git/NodeMICMAC

srun --nodes=1 singularity run --bind $PWD:/var/www  nodemicmac_latest.sif  $

````

I think multiple parts of this node are using the same port.

**Comment by kikislater** [comment]
Auto port selection is now enabled in NodeMICMAC liked in NodeODM => https://github.com/OpenDroneMap/NodeMICMAC/pull/76

![image](https://github.com/user-attachments/assets/26c96505-374e-4a7e-9729-2be35a043370)

Tested in WebODM and works as expected

![image](https://github.com/user-attachments/assets/84207ba8-7680-4775-a5f6-1e75b4b0531b)

Reopen if not working
